### ISSUE TITLE
Invalid instruction running gdlv on macOS and connecting to dlv running in Debian

### ISSUE THREAD

**Issue by leighmcculloch** [aarzilli/gdlv#45]
I'm running `dlv --headless ...` in Debian Buster in a Docker container, and then running `gdlv connect` on macOS, and when doing so the application doesn't start but instead outputs a panic.

```
SIGILL: illegal instruction
PC=0x7fff2eda88a1 m=8 sigcode=1
signal arrived during cgo execution
```

dlv OS: `Debian Buster`
dlv Go version: `go version go1.13.3 linux/amd64`
dlv Commands to run:
```
git clone https://github.com/leighmcculloch/gocheckregex
cd gocheckregex
git checkout 6b11be6c054271e7add4657d4603d1d522820ecf
dlv  --headless --listen localhost:8000 test ./. -- -test.run 'TestCheckNoGlobals$' -test.v
```

gdlv OS: `macOS Catalina`
gdlv Go version: `go version go1.13.3 darwin/amd64`
gdlv Command:
```
gdlv connect localhost:8000
```

<details><summary>Full Output</summary>

```
SIGILL: illegal instruction
PC=0x7fff2eda88a1 m=8 sigcode=1
signal arrived during cgo execution

goroutine 36 [syscall, locked to thread]:
runtime.cgocall(0x4517b50, 0xc00036e710, 0x41bc596)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc00036e6e0 sp=0xc00036e6a8 pc=0x4004eab
github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver._Cfunc_makeCurrentContext(0x5ab7b30)
	_cgo_gotypes.go:298 +0x41 fp=0xc00036e710 sp=0xc00036e6e0 pc=0x4185491
github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver.drawLoop(0xc000364120, 0x1)
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver/cocoa.go:147 +0x60 fp=0xc00036e7d0 sp=0xc00036e710 pc=0x4186540
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00036e7d8 sp=0xc00036e7d0 pc=0x405c291
created by github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver.preparedOpenGL
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver/cocoa.go:92 +0xe4

goroutine 1 [chan receive, locked to thread]:
github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver.drawgl(0x580aab0)
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver/cocoa.go:134 +0x15e
github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver._cgoexpwrap_27aa1b851ebe_drawgl(0x580aab0)
	_cgo_gotypes.go:377 +0x2b
github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver._Cfunc_startDriver()
	_cgo_gotypes.go:311 +0x41
github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver.main(0xc0001201e0, 0x400e838, 0x10)
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver/cocoa.go:107 +0x4d
github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver.Main(0xc0001201e0)
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver/gldriver.go:26 +0x2f
github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver.main(...)
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/driver_darwin.go:15
github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver.Main(...)
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/driver.go:24
github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular.(*masterWindow).Main(0xc0000bf400)
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular/shiny.go:73 +0x58
main.main()
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/main.go:1030 +0x2bb

goroutine 11 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000bf5b0, 0xc000364100, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000bf5ac)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular.(*masterWindow).main(0xc0000bf400, 0x471dfa0, 0x4b16d20)
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular/shiny.go:100 +0x2b0
github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver.driverStarted.func1()
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver/cocoa.go:114 +0x40
created by github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver.driverStarted
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver/cocoa.go:113 +0x35

goroutine 52 [chan receive]:
github.com/aarzilli/gdlv/vendor/golang.org/x/mobile/gl.(*context).enqueue(0xc000350160, 0x57, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/golang.org/x/mobile/gl/work.go:111 +0xd3
github.com/aarzilli/gdlv/vendor/golang.org/x/mobile/gl.(*context).IsProgram(0xc000350160, 0x135c00, 0x4)
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/golang.org/x/mobile/gl/gl.go:1045 +0xcb
github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver.(*screenImpl).NewTexture(0x4b16d20, 0x280, 0x1e0, 0x0, 0x0, 0x0, 0x0)
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver/screen.go:78 +0x1a0
github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver.(*windowImpl).Upload(0xc000364120, 0x0, 0x0, 0x47210e0, 0xc000360070, 0x0, 0x0, 0x280, 0x1e0)
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/golang.org/x/exp/shiny/driver/gldriver/window.go:126 +0x126
github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular.(*masterWindow).updateLocked(0xc0000bf400)
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular/shiny.go:279 +0x274
github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular.(*masterWindow).updater.func1(0xc0000bf400, 0xc00036e7c7)
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular/shiny.go:226 +0x136
github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular.(*masterWindow).updater(0xc0000bf400)
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular/shiny.go:238 +0x3c
created by github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular.(*masterWindow).main
	/Users/leighmcculloch/go/src/github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular/shiny.go:96 +0x1c8

rax    0x0
rbx    0xc00036e710
rcx    0x0
rdx    0x0
rdi    0x0
rsi    0x1f08000c
rbp    0x70000b6adef0
rsp    0x70000b6adeb0
r8     0x0
r9     0x0
r10    0x0
r11    0x0
r12    0x5ab7b30
r13    0x0
r14    0x4701932
r15    0x0
rip    0x7fff2eda88a1
rflags 0x10202
cs     0x2b
fs     0x0
gs     0x0
```
</details>

**Comment by aarzilli** [comment]
Judging from the stack trace I don't think this has anything to do with connecting to docker but instead it's a problem with shiny. What's the status of opengl on catalina btw? Weren't they thinking of removing it? You could try out the metal backend by using -tags=metal when building gdlv and see if that fares any better.

**Comment by leighmcculloch** [comment]
I think you're right. According to [this](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_intro/opengl_intro.html) looks like OpenGL was deprecated in 10.14, and by deprecated I'm guessing they mean removed entirely.

I built with `-tags=metal` and it now runs, but opens to a black screen. What's the recommended way to debug what's going on?

**Comment by aarzilli** [comment]
Shiny has a few simple examples iirc I'd test if those work first. I believe the metal driver for shiny was implemented by @dmitshur.

**Comment by dmitshur** [comment]
> I built with `-tags=metal` and it now runs, but opens to a black empty window. What's the recommended way to debug what's going on?

If it's a problem with shiny or mtldriver itself, feel free to [open an issue](https://github.com/golang/go/issues/new?title=x%2Fexp%2Fshiny%2Fdriver%2Fmtldriver%3A+) and provide reproduce steps and your setup (hardware, macOS version, etc.). We can discuss it more there.

**Comment by dmitshur** [comment]
> What's the status of opengl on catalina btw? Weren't they thinking of removing it?

OpenGL continues to be deprecated but not removed in Catalina. IMO it would be a big deal if they tried to remove it, and I don't expect it to happen very soon, at least not on Macs with GOARCH=amd64 CPUs.

FWIW, I tried the [`basic`](https://github.com/golang/exp/tree/master/shiny/example/basic) example on Catalina and it works without problems with both `gldriver` and `mtldriver`.

**Comment by leighmcculloch** [comment]
Thanks @aarzilli and @dmitshur. I've reproduced the issue using the `basic` example and have opened an issue at golang/go#35177.

**Comment by leighmcculloch** [comment]
I'm going to close this issue because it appears to be an issue in the shiny dependency and not in gdlv.
