### ISSUE TITLE
Index out of range using gdlv debug

### ISSUE THREAD

**Issue by Zettexe** [aarzilli/gdlv#79]
Window shows up for a moment then immediately crashes:

```
gdlv debug github.com/jezek/xgb/xgbgen --package xkb --gofmt=false --proto-path ./xml/src ./xml/src/xkb.xml
panic: runtime error: index out of range [5] with length 5

goroutine 25 [running]:
github.com/aarzilli/nucular/richtext.(*RichText).reflow(0xc00019a200)
	github.com/aarzilli/nucular@v0.0.0-20230531140252-73505eb2e866/richtext/draw.go:465 +0xc2d
github.com/aarzilli/nucular/richtext.(*Ctor).End(0xc00019a288)
	github.com/aarzilli/nucular@v0.0.0-20230531140252-73505eb2e866/richtext/rtxt.go:438 +0xa9e
main.(*editorWriter).Write(0xc0001ba410?, {0xc000224038, 0x5, 0x0?})
	github.com/aarzilli/gdlv/scrollback.go:47 +0x4e5
fmt.Fprintf({0x8e5e00, 0xc000200000}, {0x84396c, 0x5}, {0x0, 0x0, 0x0})
	fmt/print.go:225 +0x97
main.(*ServerDescr).Rebuild(0xb85e20)
	github.com/aarzilli/gdlv/server.go:368 +0x10d
main.(*ServerDescr).Start(0x0?)
	github.com/aarzilli/gdlv/server.go:275 +0x26
created by main.main in goroutine 1
	github.com/aarzilli/gdlv/main.go:1131 +0x425
make: *** [Makefile:62: xkb.delve] Error 2
```

**Comment by aarzilli** [comment]
I can't reproduce this. Can you add a `fmt.Printf("adding %q %d\n", string(b), scrollbackEditor.Width)` at gdlv/scrollback.go:48, so I can see if maybe I can figure it out.

Also how did you install gdlv? This doesn't look like it was installed with `go install` because it lacks the vendor directory. Were other changes made?

**Comment by Zettexe** [comment]
I installed it with the Nix package manager, should be version 1.12.0 but I don't know if there is a way to verify that with the program itself. Installing it with go install has it working perfectly well and the Nix version I cant change the code in.

**Comment by Zettexe** [comment]
Actually now it seems to be working even with the Nix installed binary... unclear on what the issue was but maybe it was using the old version?

Would be nice if we could see the version by using a command line flag maybe.

**Comment by aarzilli** [comment]
> Actually now it seems to be working even with the Nix installed binary... unclear on what the issue was but maybe it was using the old version (1.10.0)?

The stacktrace looks like it comes from the latest version. Some other thing probably changed.

> Also, doesnt quite work as expected, seem to be getting some cgo error:

This is because delve sets CGO_CFLAGS to `-O0 -g` and nix has compiler changes that force optimizations, you have to set CGO_CFLAGS to `-g` yourself.

**Comment by sikmir** [comment]
The same issue on macOS.
